/**
 * Unified Image Generation Utilities
 * Clean separation between OpenAI (DALL-E) and Google Gemini
 */

import {
  isGeminiConfigured,
  isGeminiImageModel,
  generateImageWithGemini,
  getGeminiAspectRatio,
  uploadBase64ImageToStorage,
} from "./gemini.js";

interface ImageGenerationOptions {
  prompt: string;
  model?: string;
  size?: string;
  quality?: string;
  style?: string;
}

interface ImageGenerationResult {
  imageUrl: string;
  mimeType: string;
  cost?: number;
}

/**
 * Determine which image provider to use
 */
function getImageProvider(): "openai" | "gemini" {
  const aiProvider = process.env.AI_PROVIDER || "openai";
  const imageModel = process.env.IMAGE_MODEL || "";

  // Use Gemini if explicitly set or if model name contains "gemini"
  if (aiProvider === "gemini" || isGeminiImageModel(imageModel)) {
    if (!isGeminiConfigured()) {
      console.warn("⚠️  Gemini selected for images but GEMINI_API_KEY not configured. Falling back to OpenAI.");
      return "openai";
    }
    return "gemini";
  }

  return "openai";
}

/**
 * Generate image using OpenAI DALL-E
 */
async function generateImageWithOpenAI(
  options: ImageGenerationOptions
): Promise<ImageGenerationResult> {
  const imageModel = options.model || process.env.IMAGE_MODEL || "dall-e-3";
  const imageSize = options.size || process.env.IMAGE_SIZE || "1024x1024";

  console.log(`🖼️  [OpenAI] Generating image with ${imageModel}`);
  console.log(`   Size: ${imageSize}`);
  console.log(`   Prompt: "${options.prompt.substring(0, 100)}..."`);

  const requestBody: any = {
    model: imageModel,
    prompt: options.prompt,
    n: 1,
    size: imageSize,
  };

  // Add quality parameter for DALL-E 3
  if (imageModel === "dall-e-3" && process.env.IMAGE_QUALITY) {
    requestBody.quality = process.env.IMAGE_QUALITY;
  }

  // Add style parameter for DALL-E 3
  if (imageModel === "dall-e-3" && process.env.IMAGE_STYLE) {
    requestBody.style = process.env.IMAGE_STYLE;
  }

  const startTime = Date.now();

  const response = await fetch("https://api.openai.com/v1/images/generations", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
    },
    body: JSON.stringify(requestBody),
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(
      `OpenAI API error: ${errorData.error?.message || response.statusText}`
    );
  }

  const data = await response.json();
  const url = data.data?.[0]?.url;

  if (!url) {
    throw new Error("No image URL in OpenAI response");
  }

  // Calculate cost based on model and quality
  let cost = 0.04; // Default for dall-e-3 standard
  if (imageModel === "dall-e-2") {
    cost = 0.02;
  } else if (requestBody.quality === "hd") {
    cost = 0.08;
  }

  const duration = Date.now() - startTime;
  console.log(`✅ [OpenAI] Image generated in ${duration}ms`);

  return {
    imageUrl: url,
    mimeType: "image/png",
    cost,
  };
}

/**
 * Generate image using Google Gemini
 */
async function generateImageWithGeminiProvider(
  options: ImageGenerationOptions
): Promise<ImageGenerationResult> {
  const imageModel = options.model || process.env.IMAGE_MODEL || "gemini-2.5-flash-image";
  const imageSize = options.size || process.env.IMAGE_SIZE || "1024x1024";
  const aspectRatio = getGeminiAspectRatio(imageSize);

  console.log(`🖼️  [Gemini] Generating image with ${imageModel}`);
  console.log(`   Aspect Ratio: ${aspectRatio}`);
  console.log(`   Prompt: "${options.prompt.substring(0, 100)}..."`);

  const startTime = Date.now();
  const images = await generateImageWithGemini(options.prompt, {
    model: imageModel,
    aspectRatio,
  });

  if (!images || images.length === 0) {
    throw new Error("No image generated by Gemini");
  }

  const imageData = images[0];

  // Gemini returns base64 data URLs
  const imageUrl = await uploadBase64ImageToStorage(imageData.imageData);

  // Gemini pricing: ~$0.04 per image
  const cost = 0.04;

  const duration = Date.now() - startTime;
  console.log(`✅ [Gemini] Image generated in ${duration}ms`);

  return {
    imageUrl,
    mimeType: "image/png",
    cost,
  };
}

/**
 * Main function to generate images - automatically routes to correct provider
 */
export async function generateImage(
  options: ImageGenerationOptions
): Promise<ImageGenerationResult> {
  const provider = getImageProvider();

  const startTime = Date.now();

  try {
    let result: ImageGenerationResult;

    if (provider === "gemini") {
      result = await generateImageWithGeminiProvider(options);
    } else {
      // OpenAI
      if (!process.env.OPENAI_API_KEY) {
        throw new Error("OPENAI_API_KEY not configured");
      }
      result = await generateImageWithOpenAI(options);
    }

    const duration = Date.now() - startTime;
    console.log(`✅ [Image Generation] Total time: ${duration}ms`);

    return result;
  } catch (error: any) {
    const duration = Date.now() - startTime;
    console.error(`❌ [Image Generation] Failed after ${duration}ms:`, error.message);
    throw error;
  }
}

/**
 * Helper function for backward compatibility
 */
export async function generateImageUrl(
  prompt: string,
  stylePrompt?: string,
  context?: string
): Promise<string> {
  const fullPrompt = stylePrompt
    ? `${prompt}. Style: ${stylePrompt}${context ? `. Context: ${context}` : ""}`
    : prompt;

  const result = await generateImage({ prompt: fullPrompt });
  return result.imageUrl;
}

/**
 * Generate placeholder image URL
 */
export function getPlaceholderImageUrl(text: string = "Content+Automation"): string {
  return `https://via.placeholder.com/1080x1080?text=${encodeURIComponent(text)}`;
}

